### ISSUE TITLE
uploadboy.com ads and counter

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#18]
```
uploadboy.com##.litebox
```
![Break12](https://user-images.githubusercontent.com/17685483/145533753-3bf88161-9af7-4c9d-8259-80d3748b0a1a.png)

```
uploadboy.com##+js(cookie-remover, captcha_key)
uploadboy.com##+js(cookie-remover, last_file)
||uploadboy.com/template/js/TimeCircles.js$script,1p
```
![Break13](https://user-images.githubusercontent.com/17685483/145534077-527606aa-417c-47a3-9496-8499f7103297.png)

**Comment by nimasaj** [comment]
Thanks for reporting the issue. The timer is fixed now on https://github.com/nimasaj/uBOPa/commit/39bab4a930798f7075b4bc85286b0936aa8987a6. However, I couldn't find "litebox" element getting loaded on my side. Moreover, I cannot find it in the css files of the website. Please remove the cookies on your side and check for the timer removal part after updating your filter list.

**Comment by MasterKia** [comment]
`uploadboy.com##+js(nano-setTimeout-booster.js)`
You fixed it by using this but it doesn't get rid of the timer.

https://user-images.githubusercontent.com/17685483/145557597-8b6edd89-4e94-48c0-adc4-ab718b229849.mp4

I've tried these and they seem to work:
```
uploadboy.com##+js(cookie-remover, captcha_key)
uploadboy.com##+js(cookie-remover, last_file)
||uploadboy.com/template/js/TimeCircles.js$script,1p
```

**Comment by MasterKia** [comment]
* [Example uploadboy.com download page](http://uploadboy.com/of54xzrb4dhn)

Although I've removed the cookies but this fix `uploadboy.com##+js(nano-setTimeout-booster.js)` doesn't work.
I've verified this issue on two browsers.

https://user-images.githubusercontent.com/17685483/145557937-a92d1897-eb09-4f69-80c9-e482cb4a1d5a.mp4

I've tried these and they seem to work:
```
uploadboy.com##+js(cookie-remover, captcha_key)
uploadboy.com##+js(cookie-remover, last_file)
||uploadboy.com/template/js/TimeCircles.js$script,1p
```

**Comment by MasterKia** [comment]
With regard to the "litebox" element, try (logging out from your uploadboy.com accout and) removing cookies on your side and then visit:
http://uploadboy.com/of54xzrb4dhn

![Break14](https://user-images.githubusercontent.com/17685483/145558384-c75e89aa-ec2f-4ccb-a2c7-d8db5477cf07.png)
![Break15](https://user-images.githubusercontent.com/17685483/145558394-077a9a39-bfcc-47dc-8a86-1a46136e4ab0.png)

**Comment by nimasaj** [comment]
Please close the tabs for this website, clear its cookies, comment the filters, related to it, in "My Filter" section, and test again. The timer should disappear in few seconds after being shown. Please find a short clip in the following link, `https://uploadb.me/direct/zeqoo4ncwd4u/Uploadboy_timer.mp4.html`

Regarding "litebox", is it an element or a cookie? if it's an element showing that rectangular ad box, please provide me a link that it's loaded from.

**Comment by MasterKia** [comment]
> Please close the tabs for this website **(done)**, clear its cookies **(done)**, comment the filters, related to it **(done)**, in "My Filter" section, and test again. The timer should disappear in few seconds after being shown.


https://user-images.githubusercontent.com/17685483/145564858-236868ae-4f84-4961-9134-2e33bf0287a0.mp4

**Comment by MasterKia** [comment]
> Regarding "litebox", is it an element or a cookie?

If the user clicks on the close (x) button, the page creates a cookie named "litebox" to prevent the banner from showing up again.

>  if it's an element showing that rectangular ad box,

Make sure you logout and remove all cookies for uploadboy.com and then open a download page ([example](http://uploadboy.com/of54xzrb4dhn)).

> please provide me a link that it's loaded from.

http://uploadboy.com/template/img/welcome2purchase.png

![Break16](https://user-images.githubusercontent.com/17685483/145565488-38060439-83b9-4fb3-8f54-47e1ba723ecd.png)
![Break17](https://user-images.githubusercontent.com/17685483/145565485-7abb3eb7-41d2-473a-9de8-b28425e9a4a1.png)

**Comment by nimasaj** [comment]
Since the "litebox" is not loaded on my side, I cannot test for it. Please check with the following filter if it works for you. If so, then I will add it to the list. 
`uploadboy.com##div[class^="litebox"]`
Regarding your last video clip, I wonder why the captcha is not loaded on your side. It could be the reason why the download link is not generated on your side. The timer is successfully boosted and disappears in a few seconds, although, the final download link is not generated and the page reloads after clicking the download button. Could you please check in Google Chrome and report the result? I hope that the captcha will be loaded in Google Chrome on your side. Isn't JS limited on this website (e.g. by another extension or browser configuration)?
If the website is working with following filters on your side, then it's a cookie problem for you, since the first two filters are only removing the cookies, and the last one is blocking js file for the timer. If "TimeCircles.js" is blocked, then download link cannot be generated.

```
uploadboy.com##+js(cookie-remover, captcha_key)
uploadboy.com##+js(cookie-remover, last_file)
||uploadboy.com/template/js/TimeCircles.js$script,1p
```

By the way, I, also, tested in FF 94 and the timer is boosted and download link is generated without an issue.

**Comment by MasterKia** [comment]
Google chrome fresh install (watch the video on 1.5x speed if you will):

https://user-images.githubusercontent.com/17685483/145576253-72ab9f96-ab89-4363-abca-90110d691569.mp4

**Comment by nimasaj** [comment]
As it seems Google captcha is only loaded for the first time on your side. Could it be due to different OS/network configurations (e.g. manipulation, redirect, censorship or etc.), I'm not sure. But, the weird part is that blocking TimeCircles.js on your side works, but not on my side, as it's shown in the following video.
`https://uploadb.me/direct/fegy7dywfjpr/Uploadboy_timer2.rar.html`

Please check out which of the following combinations works for you.

```
uploadboy.com##+js(cookie-remover, captcha_key)
uploadboy.com##+js(nano-setTimeout-booster.js)
```

```
uploadboy.com##+js(cookie-remover, last_file)
uploadboy.com##+js(cookie-remover, captcha_key)
uploadboy.com##+js(nano-setTimeout-booster.js)
```

```
uploadboy.com##+js(cookie-remover, last_file)
uploadboy.com##+js(cookie-remover, captcha_key)
||uploadboy.com/template/js/TimeCircles.js$script,1p
uploadboy.com##+js(nano-setTimeout-booster.js)
```

Also, please check out for Google Captcha in your log, when reloading the page, if it's called.
`https://gcdn.pbrd.co/images/furlQ3YAeJVH.png?o=1`

**Comment by MasterKia** [comment]
> due to different OS/network configurations (e.g. manipulation, redirect, censorship or etc.)

Could that be the cause on **_your_** side? Because it appears that you're using a VPN because:
1) uploadboy.com is in English for you and not Persian
2) google.com says "Google offered in dansk"
3) Also the "litebox" thing (https://github.com/nimasaj/uBOPa/issues/18#issuecomment-990882872) doesn't show up for you because to the eyes of the site you're a foreigner visiter and not a Iranian one.

**Comment by nimasaj** [comment]
I'm not located in Iran. 
If you can test the combinations above, please share the result with me.

**Comment by MasterKia** [comment]
All of those different combinations work.

Also this works by itself (test on Edge, Chrome, Firefox):
`uploadboy.com##+js(cookie-remover, captcha_key)`

So I think this would be adequate:
```
uploadboy.com##+js(cookie-remover, captcha_key)
uploadboy.com##.litebox
```

**Comment by nimasaj** [comment]
Thanks for your cooperation. It's fixed on https://github.com/nimasaj/uBOPa/commit/b08873807024729e22880c6051894a2f0f5a1778.

**Comment by MasterKia** [comment]
@nimasaj Disable previous filters, test:
```adb
uploadboy.com##+js(ra, disabled, #btn_download)
uploadboy.com##.time_circles
uploadboy.com##[id^="mediaad"]:upward(.text-center)
```

```
https://uploadboy.com/z3d37va4zekk
https://uploadboy.com/2qlpkh55ozp6.html
https://uploadboy.com/eir8i7qp7m28
```
